on: 
  workflow_dispatch:
    inputs:
      engine_sha:
        description: 'engine hash'     
        required: true
      branch:
        description: 'branch name of flutter and engine repo, where the engine->flutter roll happens'     
        required: false
        default: 'master'

jobs:
  roll-engine-to-framework:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Framework Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.inputs.branch }}
          repository: flutter/flutter
          token: ${{ github.token }}
          path: flutter
      - name: Update Engine version
        working-directory: ./flutter
        run: |
          echo "PREV_VERSION=$(cat bin/internal/engine.version | tr -d '\n')" >> $GITHUB_ENV
          echo "${{ github.event.inputs.engine_sha }}" > bin/internal/engine.version
      - name: Checkout Engine History
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.inputs.branch }}
          repository: flutter/engine
          token: ${{ github.token }}
          path: engine
          fetch-depth: 100
      - name: Log Engine Commits
        working-directory: ./engine
        run: |
          git branch
          git log --oneline -10
          git log --no-decorate --oneline $PREV_VERSION..$ENGINE_SHA | tr '\n' '<br>'
          echo "COMMIT_HISTORY=$(git log --no-decorate --oneline $PREV_VERSION..${{ github.event.inputs.engine_sha }} | tr '\n' '<br>')" >> $GITHUB_ENV
        env:
          ENGINE_SHA: ${{ github.event.inputs.engine_sha }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          path: flutter
          token: ${{ secrets.PAT }}
          commit-message: Roll engine to ${{ github.event.inputs.engine_sha }}
          committer: GitHub <noreply@github.com>
          title: 'Roll engine to ${{ github.event.inputs.engine_sha }}'
          body: |
            flutter engine->framework roll
            - branch: ${{ github.event.inputs.branch }}
            - engine hash: ${{ github.event.inputs.engine_sha }}
            commit history: 
            ${{ github.env.COMMIT_HISTORY }}

