on: workflow_dispatch

# TODO: the bot on dart should have permission to open PR on flutter/engine.

jobs:
  roll-engine:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Flutter Engine Repo
        uses: actions/checkout@v4
        with:
          ref: beta
          repository: flutter/flutter
          token: ${{ github.token }}
      - name: Read Beta Candidate Name
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./bin/internal/release-candidate-branch.version
      - name: Set Beta Branch
        run: |
          echo "BETA_BRANCH=${{ steps.version.outputs.content }}" >> $GITHUB_ENV
      - name: Trim Ending newline
        run: |
          echo "BETA_BRANCH=$(echo $BETA_BRANCH | tr -d '\n')" >> $GITHUB_ENV
      # Note: flutter/engine doesn't have a beta branch.
      - name: Checkout flutter/engine Repo
        uses: actions/checkout@v4
        with:
          ref: ${BETA_BRANCH}
          repository: flutter/engine
          token: ${{ github.token }}
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      # https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
      # github.event.after has the latest dart hash.
      - name: Store Dart Hash
        run: |
          echo "DART_HASH=AFTER_HASH_PLACEHOLDER" >> $GITHUB_ENV
          echo "PREV_HASH=668bef34e453fc84ab9fa572d917110b51fa88eb" >> $GITHUB_ENV
      - name: Update Dart Hash
        run: |
          sed -i "s/${PREV_HASH}/${DART_HASH}/g" DEPS
          cat DEPS | grep ${DART_HASH}
          cat DEPS | grep ${PREV_HASH}
      # https://github.com/flutter/engine/tree/main/tools/licenses
      # - name: Run license script
      #   run: |
      #     cd engine/tools/licenses
      #     dart pub get
      #     gclient sync -D
      #     rm -rf ../../../out/licenses
      #     dart --enable-asserts lib/main.dart --src ../../.. --out ../../../out/licenses --golden ../../ci/licenses_golden
      # - name: Inspect License content change
      #   run: |
      #     cp ../../../out/licenses/* ../../ci/licenses_golden
      #     git diff
      # - name: Create Engine PR
      #   run: |
      #     git --version
      #     git checkout -b roll-dart-${DART_HASH} --track origin/${BETA_BRANCH}
      #     git status
      #     git add .
      #     git status
      #     git commit -m "roll dart to ${DART_HASH}"
      #     git status
      #     git push -u origin roll-dart-${DART_HASH}
      #     gh pr create --title "[test PR for github actions]roll dart hash to ${DART_HASH}" --body "cc @XilaiZhang"
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}


