on: workflow_dispatch

permissions: read-all

jobs:
  cp_beta:
    name: cp_beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Checkout Flutter Beta
        uses: actions/checkout@v4
        with:
          ref: beta
          repository: flutter/flutter
          token: ${{ github.token }}
      - name: Read Beta Candidate Name
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./bin/internal/release-candidate-branch.version
      - name: Echo Beta Branch
        # for some reasons https://stackoverflow.com/questions/57968497 doesn't work
        run: |
          echo "${{ steps.version.outputs.content }}"
          echo "BETA_BRANCH=${{ steps.version.outputs.content }}" >> $GITHUB_ENV
      # i need to trim the ending newline
      - name: Verify Beta Branch
        run: |
          echo "BETA_BRANCH=$(echo $BETA_BRANCH | tr -d '\n')" >> $GITHUB_ENV
          echo $BETA_BRANCH
      - name: Get Approver
        run: |
          RAW_APPROVERS=$(gh pr view --json reviews -q ".reviews[] | select(.state == \"APPROVED\") | .author.login" -R flutter/flutter 136658 --comments)
          echo "APPROVERS=$(echo $RAW_APPROVERS | sed 's/ /,/g')" >> $GITHUB_ENV
          echo $APPROVERS
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Verify Approver
        run: |
          echo $APPROVERS
      - name: Checkout Flutter master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ github.token }}
      - name: Cherry Pick to Beta
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: ${BETA_BRANCH}
          # we can add a label here
          reviewers: ${APPROVERS}
          title: "[flutter-release][beta-cherrypick]${{ github.event.pull_request.title }}"
          body: 'Cherry picking #{old_pull_request_id} onto beta release candidate branch. cc @${{ github.event.pull_request.user.login }}'
