on: 
  workflow_dispatch

permissions: write-all

jobs:
  minimal-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current Repo
        uses: actions/checkout@v4
        with:
          ref: master
          repository: XilaiZhang/miscellaneous-side-project
          token: ${{ github.token }}
          path: flutter
      - name: Write some randome file
        run: |
          cd flutter
          touch empty.json
      - name: Create PR with plain token
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.PAT}}
          commit-message: blah
          committer: GitHub <noreply@github.com>
          title: 'github actions test'
          path: flutter
